spring.application.name=${APPLICATION_NAME}
spring.ai.ollama.base-url=${SPRING_AI_OLLAMA_BASE_URL}
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USER_NAME}
spring.datasource.password=${DATA_SOURCE_USER_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.ai.retry.max-attempts=1

# Retry config
resilience4j.retry.instances.ollamaChat.max-attempts=3
resilience4j.retry.instances.ollamaChat.wait-duration=2s

# Circuit breaker config
resilience4j.circuitbreaker.instances.ollamaChat.sliding-window-size=5
resilience4j.circuitbreaker.instances.ollamaChat.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ollamaChat.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.ollamaChat.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.ollamaChat.minimum-number-of-calls=3

# Retry config - for embedding
resilience4j.retry.instances.ollamaEmbedding.max-attempts=3
resilience4j.retry.instances.ollamaEmbedding.wait-duration=2s

# Circuit breaker config - for embedding
resilience4j.circuitbreaker.instances.ollamaEmbedding.sliding-window-size=5
resilience4j.circuitbreaker.instances.ollamaEmbedding.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ollamaEmbedding.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.ollamaEmbedding.minimum-number-of-calls=3